#!/bin/bash

# Test script for go-pdf service
# This script tests the PDF generation API with a sample HTML document

echo "Testing go-pdf service..."
echo ""

# Check if service is running
echo "Checking if service is available..."
curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/ > /dev/null 2>&1
if [ $? -ne 0 ]; then
    echo "Error: Service is not running on http://localhost:8080"
    echo "Please start the service with: docker-compose up -d"
    exit 1
fi

echo "Service is running!"
echo ""

# Create test HTML
HTML_CONTENT='<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Go-PDF Test Document</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
            line-height: 1.6;
        }
        .header {
            background-color: #4CAF50;
            color: white;
            padding: 20px;
            text-align: center;
            border-radius: 5px;
        }
        .content {
            background-color: #f5f5f5;
            padding: 20px;
            margin-top: 20px;
            border-radius: 5px;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 12px;
            color: #666;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 20px;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #4CAF50;
            color: white;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Go-PDF Service Test</h1>
        <p>HTML to PDF Conversion Demo</p>
    </div>

    <div class="content">
        <h2>Features Demonstrated</h2>
        <ul>
            <li>HTML5 support</li>
            <li>CSS styling and layout</li>
            <li>Custom fonts and colors</li>
            <li>Tables and lists</li>
            <li>Responsive design elements</li>
        </ul>

        <h2>Sample Table</h2>
        <table>
            <thead>
                <tr>
                    <th>Feature</th>
                    <th>Status</th>
                    <th>Notes</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>HTML Rendering</td>
                    <td>✓ Working</td>
                    <td>Full HTML5 support</td>
                </tr>
                <tr>
                    <td>CSS Styling</td>
                    <td>✓ Working</td>
                    <td>CSS3 compatible</td>
                </tr>
                <tr>
                    <td>JavaScript</td>
                    <td>✓ Working</td>
                    <td>Executed before rendering</td>
                </tr>
            </tbody>
        </table>
    </div>

    <div class="footer">
        <p>Generated by go-pdf service | Powered by wkhtmltopdf</p>
    </div>
</body>
</html>'

echo "Generating PDF from HTML..."
echo ""

# Make API call
RESPONSE=$(curl -s -w "\n%{http_code}" -X POST http://localhost:8080/api/v1/generate \
    -H "Content-Type: text/html" \
    -d "$HTML_CONTENT" \
    -o test-output.pdf)

HTTP_CODE=$(echo "$RESPONSE" | tail -n1)

if [ "$HTTP_CODE" -eq 200 ]; then
    echo "✓ Success! PDF generated successfully"
    echo "  Output file: test-output.pdf"
    echo "  File size: $(du -h test-output.pdf | cut -f1)"
    echo ""
    echo "You can now open test-output.pdf to view the result."
else
    echo "✗ Error: HTTP $HTTP_CODE"
    echo "Please check the service logs: docker logs go-pdf"
    exit 1
fi
